	ORG 0
	SJMP PROG
	
	ORG 0003H
	SJMP EXT0
	
	ORG 000BH
	SJMP TIM0
	
	ORG 0013H
	SJMP EXT1

PROG:	MOV P1, #00H
	MOV TCON, #00000101B
	MOV TMOD, #00000001B
	MOV TH0, #00H
	MOV TL0, #00H
	MOV IE, #10000111B
	SETB P1.1 ;COMECA A ENCHER

LOOP:	SJMP LOOP

	
EXT0:	CLR EA
	SETB TR0 ;COMECO A CONTAR O TEMPO
	SETB EA
	RETI

EXT1:	CLR EA
	CLR P1.1 ;PARA DE ENCHER
	CLR TR0
	
	MOV B, #2H ; DIVIDO O THO POR 2, SUBTRAIO O VALOR DE #FF E DEPOIS ATUALIZO O THO COM O TEMPO PARA DESENCHER ATE A METADE
	MOV A, TH0
	DIV AB
	MOV R0, A
	MOV A, #0FFH
	SUBB A, R0
	MOV R0, A
	
	MOV B, #2H ; DIVIDO O TLO POR 2, SUBTRAIO O VALOR DE #FF E DEPOIS ATUALIZO O THO COM O TEMPO PARA DESENCHER ATE A METADE
	MOV A, TL0
	DIV AB
	MOV R1, A
	MOV A, #0FFH
	SUBB A, R1
	MOV R1, A

	MOV TH0, R0 ; ATUALIZO OS CONTADORES
	MOV TL0, R1
	SETB TR0
	SETB P1.0 ;COMECA A DESENCHER
	SETB EA
	RETI

TIM0:	CLR EA
	CLR P1.0 ;PARA DE DESENCHER - NA METADE
	CLR TR0
	RETI
	END