	ORG 0
	MOV DPTR, #DATA
	CLR A
	MOVC A, @A+DPTR
	MOV 25H, A
	INC DPTR
	CLR A
	MOVC A, @A+DPTR
	MOV DPTR, #1200H
	CJNE A, 25H, DIF
	SJMP FIM ;SE FOREM IGUAIS NAO FACO NADA
DIF:	JC A_MEN ;SE O QUE TA NO ACUMULADOR FOR MENOR VOU PARA A_MEN E PASSO O QUE ESTA NO ACC
	MOV A, 25H ;SE NAO PASSAREI O QUE ESTA EM 25H
	MOVX @DPTR, A
	SJMP FIM
A_MEN:	MOVX @DPTR, A
FIM:	SJMP FIM
DATA:	DB 1DH, 0CH
	END